### ISSUE TITLE
Availability 1.0

### ISSUE THREAD

**Issue by chrisbenincasa** [chrisbenincasa/teletracker#753]
Umbrella issue tracking availability overall.

### Netflix
- [ ] Determine why we always miss a chunk of items on Netflix scrape #747
- [ ] Add marker as to whether item is Netflix original in scraper #705
- [ ] Designate whether Netflix item is available in 4K in crawler #716

### Amazon / Prime
- [ ] Overall availability #308 
- [ ] #749
- [ ] https://github.com/chrisbenincasa/teletracker/issues/752

### Google Play Store / YouTube
